monitoring/prometheus.yml  global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'local_business_service'
    static_configs:
      - targets: ['local_business_service:8000']


# === ORCHESTRATOR SERVICE ===
  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:9091']

# === POSTGRESQL ===
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']

# === BUSINESS METRICS ===
  - job_name: 'business_metrics'
    static_configs:
      - targets: ['prometheus_exporter:9100']
    scrape_interval: 10s

alert_files:
  - '/etc/prometheus/rules/*.yml'
